Resolve bare_trait_objects error (2021 edition)
This can be triggered when deriving Deserialize with rust 2021 edition:

error[E0783]: trait objects without an explicit `dyn` are deprecated
 --> src/main.rs:7:10
  |
7 | #[derive(Deserialize)]
  |          ^^^^^^^^^^^ help: use `dyn`: `<dyn Deserialize>`
  |