Install newest build of cargo-outdated
The old version available by default in the GitHub Actions image fails
with:

    thread 'main' panicked at 'package cache lock is not currently held, Cargo forgot to call `acquire_package_cache_lock` before we got to this stack frame', /usr/share/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.57.0/src/cargo/util/config/mod.rs:1542:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace