Ignore assertions_on_result_states clippy lint
    error: called `assert!` with `Result::is_ok`
      --> tests/regression/issue24.rs:12:5
       |
    12 |     assert!(result.is_ok());
       |     ^^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `result.unwrap()`
       |
       = note: `-D clippy::assertions-on-result-states` implied by `-D clippy::all`
       = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assertions_on_result_states

    error: called `assert!` with `Result::is_err`
     --> tests/regression/issue9.rs:6:5
      |
    6 |     assert!(result.is_err());
      |     ^^^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `result.unwrap_err()`
      |
      = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assertions_on_result_states